server:
  port: 8000

spring:
  kafka:
    bootstrap-servers: localhost:9092

topic:
  message:
    name: message
  filtered-message:
    name: filtered-message
  partitioned-message:
    name: partitioned-message
  greeting:
    name: greeting
  multi-type:
    name: multi-type